// <auto-generated /> // Tämä osoittaa, että tiedosto on automaattisesti generoitu eikä sitä yleensä tarvitse manuaalisesti muokata.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsedPhonesShopAPI.Data;

#nullable disable // Estää null-arvojen käsittelyn C# 8.0:n nullable-huomautuksia käyttämällä.

namespace UsedPhonesShopAPI.Migrations
{
    // Määrittää, että tämä migraatio liittyy ApplicationDbContextiin.
    [DbContext(typeof(ApplicationDbContext))]
    // Tämä määrittää migraation version tunnisteen.
    [Migration("20240917081019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) // Määrittelee tietokannan rakenteen eli kohdemallin.
        {
#pragma warning disable 612, 618 // Poistaa käytöstä varoitukset vanhentuneista ominaisuuksista tämän osion koodissa.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8"); // Lisää annotaation, joka osoittaa käytetyn Entity Framework Core -version.

            // Määrittää roolitaulun rakenteen (AspNetRoles).
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    // "Id" on roolin yksilöllinen tunniste.
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // "ConcurrencyStamp" hallitsee samanaikaisia päivityksiä.
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken() // Merkitään samanaikaisuuden hallintaan käytettäväksi tokeniksi.
                        .HasColumnType("TEXT");

                    // "Name" on roolin nimi.
                    b.Property<string>("Name")
                        .HasMaxLength(256) // Roolin nimi voi olla enintään 256 merkkiä pitkä.
                        .HasColumnType("TEXT");

                    // "NormalizedName" on roolin normalisoitu nimi, jota käytetään hakemiseen.
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Luodaan hakemisto normalisoidulle nimelle tehokasta hakemista varten.
                    b.HasIndex("NormalizedName")
                        .IsUnique() // Varmistetaan, että roolin nimi on ainutlaatuinen.
                        .HasDatabaseName("RoleNameIndex"); // Hakemiston nimi tietokannassa.

                    // Määrittää taulun nimen.
                    b.ToTable("AspNetRoles", (string)null);
                });

            // Määrittää taulun rooliväitteille (AspNetRoleClaims).
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    // "Id" on rooliväitteen yksilöllinen tunniste.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd() // Arvo generoidaan automaattisesti (autoincrement).
                        .HasColumnType("INTEGER");

                    // "ClaimType" on väitteen tyyppi.
                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    // "ClaimValue" on väitteen arvo.
                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    // "RoleId" on roolin tunniste, johon väite liittyy.
                    b.Property<string>("RoleId")
                        .IsRequired() // Varmistaa, että roolitunniste on pakollinen.
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Luodaan hakemisto roolitunnisteelle.
                    b.HasIndex("RoleId");

                    // Määrittää taulun nimen.
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            // Määrittää käyttäjätaulun (AspNetUsers).
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    // "Id" on käyttäjän yksilöllinen tunniste.
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // "AccessFailedCount" on epäonnistuneiden kirjautumisyritysten laskuri.
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    // "ConcurrencyStamp" hallitsee samanaikaisia päivityksiä.
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken() // Merkitään samanaikaisuuden hallintaan käytettäväksi tokeniksi.
                        .HasColumnType("TEXT");

                    // "Email" on käyttäjän sähköpostiosoite.
                    b.Property<string>("Email")
                        .HasMaxLength(256) // Sähköpostiosoitteen maksimipituus on 256 merkkiä.
                        .HasColumnType("TEXT");

                    // "EmailConfirmed" osoittaa, onko sähköposti vahvistettu.
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    // "LockoutEnabled" osoittaa, onko käyttäjätilin lukitus käytössä.
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    // "LockoutEnd" määrittelee, milloin tilin lukitus päättyy.
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    // "NormalizedEmail" on normalisoitu sähköposti.
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "NormalizedUserName" on normalisoitu käyttäjänimi.
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "PasswordHash" tallentaa käyttäjän salasanan tiivisteen.
                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    // "PhoneNumber" on käyttäjän puhelinnumero.
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    // "PhoneNumberConfirmed" osoittaa, onko puhelinnumero vahvistettu.
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    // "SecurityStamp" on turvatunniste.
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    // "TwoFactorEnabled" osoittaa, onko kaksivaiheinen tunnistautuminen käytössä.
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    // "UserName" on käyttäjän käyttäjänimi.
                    b.Property<string>("UserName")
                        .HasMaxLength(256) // Käyttäjänimen maksimipituus on 256 merkkiä.
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Luodaan hakemisto normalisoidulle sähköpostille tehokasta hakemista varten.
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    // Luodaan hakemisto normalisoidulle käyttäjänimelle ja varmennetaan, että se on ainutlaatuinen.
                    b.HasIndex("NormalizedUserName")
                        .IsUnique() // Varmistetaan, että käyttäjänimi on ainutlaatuinen.
                        .HasDatabaseName("UserNameIndex");

                    // Määrittää taulun nimen.
                    b.ToTable("AspNetUsers", (string)null);
                });

            // Muut entityt ja niiden määrittelyt jatkavat samalla logiikalla...

#pragma warning restore 612, 618 // Ota varoitukset taas käyttöön lopussa.
        }
    }
}
