// <auto-generated /> // Tämä tiedosto on automaattisesti generoitu, eikä sitä yleensä tarvitse manuaalisesti muokata.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsedPhonesShopAPI.Data;

#nullable disable // Poistaa nullable-huomautusten käytön tässä tiedostossa.

namespace UsedPhonesShopAPI.Migrations
{
    // Määrittää, että tämä migraatio liittyy ApplicationDbContextiin.
    [DbContext(typeof(ApplicationDbContext))]

    // Tämä attribuutti määrittää migraation version tunnisteen.
    [Migration("20240917084609_IdentitySetup")]
    partial class IdentitySetup
    {
        /// <inheritdoc />
        // Tämä metodi luo tietokantamallin, joka vastaa sovelluksen entiteettimallia.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618 // Poistaa varoitukset vanhentuneista ominaisuuksista tämän osion koodissa.

            // Määrittää käytetyn Entity Framework Core -version annotaation tietokantaan.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            // Määrittelee "IdentityRole"-entiteetin eli roolitietokannan rakenteen.
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    // "Id" on roolin yksilöllinen tunniste.
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // "ConcurrencyStamp" hallitsee samanaikaisia päivityksiä.
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken() // Tämä kenttä toimii samanaikaisuuden hallintaan.
                        .HasColumnType("TEXT");

                    // "Name" on roolin nimi, joka voi olla enintään 256 merkkiä pitkä.
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "NormalizedName" on roolin normalisoitu nimi, joka voi olla enintään 256 merkkiä pitkä.
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Määrittää hakemiston normalisoidulle nimelle (Unique constraint), jotta roolinimi on ainutlaatuinen.
                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex"); // Tietokannan hakemiston nimi.

                    // Määrittää taulun nimen.
                    b.ToTable("AspNetRoles", (string)null);
                });

            // Määrittelee "IdentityRoleClaim"-entiteetin eli rooliväitteet.
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    // "Id" on väitteen yksilöllinen tunniste.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd() // Arvo generoidaan automaattisesti.
                        .HasColumnType("INTEGER");

                    // "ClaimType" on väitteen tyyppi.
                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    // "ClaimValue" on väitteen arvo.
                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    // "RoleId" on roolin tunniste, johon väite liittyy.
                    b.Property<string>("RoleId")
                        .IsRequired() // Tämä kenttä on pakollinen.
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Määrittää hakemiston roolitunnisteelle.
                    b.HasIndex("RoleId");

                    // Määrittää taulun nimen.
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            // Määrittelee "IdentityUser"-entiteetin eli käyttäjät.
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    // "Id" on käyttäjän yksilöllinen tunniste.
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // "AccessFailedCount" tallentaa epäonnistuneiden kirjautumisyritysten määrän.
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    // "ConcurrencyStamp" hallitsee samanaikaisia päivityksiä.
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken() // Tämä kenttä toimii samanaikaisuuden hallintaan.
                        .HasColumnType("TEXT");

                    // "Email" on käyttäjän sähköpostiosoite, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "EmailConfirmed" osoittaa, onko sähköposti vahvistettu.
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    // "LockoutEnabled" osoittaa, onko käyttäjätilin lukitus käytössä.
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    // "LockoutEnd" määrittelee tilin lukituksen päättymisajan.
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    // "NormalizedEmail" on normalisoitu sähköpostiosoite, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "NormalizedUserName" on normalisoitu käyttäjänimi, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "PasswordHash" tallentaa käyttäjän salasanan tiivisteen.
                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    // "PhoneNumber" on käyttäjän puhelinnumero.
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    // "PhoneNumberConfirmed" osoittaa, onko puhelinnumero vahvistettu.
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    // "SecurityStamp" on turvatunniste.
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    // "TwoFactorEnabled" osoittaa, onko kaksivaiheinen tunnistautuminen käytössä.
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    // "UserName" on käyttäjän käyttäjänimi, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Määrittää hakemiston normalisoidulle sähköpostille.
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    // Määrittää hakemiston normalisoidulle käyttäjänimelle ja varmistaa, että se on ainutlaatuinen.
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    // Määrittää taulun nimen.
                    b.ToTable("AspNetUsers", (string)null);
                });

            // Määrittelee muut entiteetit samalla logiikalla...

#pragma warning restore 612, 618 // Ota varoitukset taas käyttöön lopussa.
        }
    }
}
