// <auto-generated /> // Tämä tiedosto on automaattisesti generoitu, eikä sitä yleensä tarvitse muokata käsin.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsedPhonesShopAPI.Data;

#nullable disable // Poistaa nullable-huomautukset käytöstä tässä tiedostossa.

namespace UsedPhonesShopAPI.Migrations
{
    // Tämä luokka toimii migraation tilannekuvana (snapshot) tietokannan nykytilasta, ja sitä käytetään vertailemaan mahdollisia muutoksia tulevissa migraatioissa.
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        // Tämä metodi rakentaa tietokantamallin (ModelBuilder), joka kuvaa tietokannan rakenteen.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618 // Poistaa varoitukset vanhentuneista ominaisuuksista tässä osassa.

            // Määrittelee käytetyn Entity Framework Core -version annotaation.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            // Määrittelee "IdentityRole"-entiteetin eli roolitietokannan rakenteen.
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    // "Id" on roolin yksilöllinen tunniste (ensisijainen avain).
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // "ConcurrencyStamp" on samanaikaisuuden hallintaan liittyvä token.
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken() // Tunnistetaan kenttä samanaikaisuuden hallintaan.
                        .HasColumnType("TEXT");

                    // "Name" on roolin nimi, joka voi olla enintään 256 merkkiä pitkä.
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "NormalizedName" on normalisoitu roolin nimi, joka voi olla enintään 256 merkkiä pitkä.
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Määrittää hakemiston normalisoidulle nimelle ja varmistaa, että se on ainutlaatuinen.
                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex"); // Hakemiston nimi tietokannassa.

                    // Määrittelee taulun nimen tietokantaan.
                    b.ToTable("AspNetRoles", (string)null);
                });

            // Määrittelee "IdentityRoleClaim"-entiteetin eli rooliväitteet (claims).
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    // "Id" on väitteen yksilöllinen tunniste (ensisijainen avain).
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd() // Arvo generoidaan automaattisesti (autoincrement).
                        .HasColumnType("INTEGER");

                    // "ClaimType" on väitteen tyyppi.
                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    // "ClaimValue" on väitteen arvo.
                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    // "RoleId" on roolitunniste, johon väite liittyy.
                    b.Property<string>("RoleId")
                        .IsRequired() // Tämä kenttä on pakollinen.
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Määrittää hakemiston roolitunnisteelle.
                    b.HasIndex("RoleId");

                    // Määrittelee taulun nimen tietokantaan.
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            // Määrittelee "IdentityUser"-entiteetin eli käyttäjät.
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    // "Id" on käyttäjän yksilöllinen tunniste (ensisijainen avain).
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    // "AccessFailedCount" tallentaa epäonnistuneiden kirjautumisyritysten määrän.
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    // "ConcurrencyStamp" hallitsee samanaikaisia päivityksiä.
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken() // Tämä kenttä toimii samanaikaisuuden hallintaan.
                        .HasColumnType("TEXT");

                    // "Email" on käyttäjän sähköpostiosoite, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "EmailConfirmed" osoittaa, onko sähköpostiosoite vahvistettu.
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    // "LockoutEnabled" osoittaa, onko käyttäjätilin lukitus käytössä.
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    // "LockoutEnd" määrittelee tilin lukituksen päättymisajan.
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    // "NormalizedEmail" on normalisoitu sähköpostiosoite, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "NormalizedUserName" on normalisoitu käyttäjänimi, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "PasswordHash" tallentaa käyttäjän salasanan tiivisteen.
                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    // "PhoneNumber" on käyttäjän puhelinnumero.
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    // "PhoneNumberConfirmed" osoittaa, onko puhelinnumero vahvistettu.
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    // "SecurityStamp" on turvatunniste.
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    // "TwoFactorEnabled" osoittaa, onko kaksivaiheinen tunnistautuminen käytössä.
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    // "UserName" on käyttäjän käyttäjänimi, jonka maksimipituus on 256 merkkiä.
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    // "Id" on ensisijainen avain.
                    b.HasKey("Id");

                    // Määrittää hakemiston normalisoidulle sähköpostille.
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    // Määrittää hakemiston normalisoidulle käyttäjänimelle ja varmistaa, että se on ainutlaatuinen.
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    // Määrittelee taulun nimen tietokantaan.
                    b.ToTable("AspNetUsers", (string)null);
                });

            // Määrittelee muut entiteetit samalla logiikalla...

#pragma warning restore 612, 618 // Ota varoitukset taas käyttöön lopussa.
        }
    }
}
